package com.vuelosfis.view;

import java.awt.BorderLayout;

/**
 *
 * @author Usuario
 */
public class AdministradorVentanaView extends javax.swing.JFrame {

    private com.vuelosfis.controller.SistemaController controller;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdministradorVentanaView.class.getName());

    
    
    /**
     * Creates new form AdministradorVentanaView
     */
    public AdministradorVentanaView(com.vuelosfis.controller.SistemaController controller) {
        this.controller = controller;
        initComponents();
        this.setLocationRelativeTo(null); // Centrar ventana
        this.setTitle("VuelosFIS - Panel de Administración");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        verVueloBtn = new javax.swing.JButton();
        cargarVueloBtn = new javax.swing.JButton();
        cerrarBtn = new javax.swing.JButton();
        actualizarDatosBtn = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(124, 201, 210));

        verVueloBtn.setBackground(new java.awt.Color(119, 144, 225));
        verVueloBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        verVueloBtn.setForeground(new java.awt.Color(51, 51, 51));
        verVueloBtn.setText("Ver Vuelos");
        verVueloBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        verVueloBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verVueloBtn.setFocusPainted(false);
        verVueloBtn.setPreferredSize(new java.awt.Dimension(500, 150));
        verVueloBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verVueloBtnActionPerformed(evt);
            }
        });

        cargarVueloBtn.setBackground(new java.awt.Color(119, 144, 225));
        cargarVueloBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        cargarVueloBtn.setForeground(new java.awt.Color(51, 51, 51));
        cargarVueloBtn.setText("Cargar CSV de Vuelos");
        cargarVueloBtn.setToolTipText("");
        cargarVueloBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        cargarVueloBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargarVueloBtn.setFocusPainted(false);
        cargarVueloBtn.setPreferredSize(new java.awt.Dimension(500, 150));
        cargarVueloBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cargarVueloBtnMouseDragged(evt);
            }
        });
        cargarVueloBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarVueloBtnActionPerformed(evt);
            }
        });

        cerrarBtn.setBackground(new java.awt.Color(255, 51, 51));
        cerrarBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        cerrarBtn.setForeground(new java.awt.Color(204, 204, 204));
        cerrarBtn.setText("Cerrar Sesión");
        cerrarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        cerrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarBtn.setFocusPainted(false);
        cerrarBtn.setPreferredSize(new java.awt.Dimension(500, 150));

        actualizarDatosBtn.setBackground(new java.awt.Color(119, 144, 225));
        actualizarDatosBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        actualizarDatosBtn.setForeground(new java.awt.Color(51, 51, 51));
        actualizarDatosBtn.setText("Actualizar Datos");
        actualizarDatosBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        actualizarDatosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarDatosBtn.setFocusPainted(false);
        actualizarDatosBtn.setPreferredSize(new java.awt.Dimension(500, 150));
        actualizarDatosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarDatosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1145, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargarVueloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verVueloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarDatosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cargarVueloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(verVueloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(actualizarDatosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cerrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarVueloBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarVueloBtnActionPerformed
        // TODO add your handling code here:
        Panel1 p1 = new Panel1();
        p1.setSize(1145, 700);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_cargarVueloBtnActionPerformed

    private void cargarVueloBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarVueloBtnMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarVueloBtnMouseDragged

    private void verVueloBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verVueloBtnActionPerformed
        // TODO add your handling code here:
        Panel2 p2 = new Panel2();
        p2.setSize(1145, 700);
        p2.setLocation(0, 0);

        content.removeAll();
        content.add(p2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_verVueloBtnActionPerformed

    private void actualizarDatosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarDatosBtnActionPerformed
        // TODO add your handling code here:
        Panel3 p3 = new Panel3();
        p3.setSize(1145, 700);
        p3.setLocation(0, 0);

        content.removeAll();
        content.add(p3, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_actualizarDatosBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarDatosBtn;
    private javax.swing.JButton cargarVueloBtn;
    private javax.swing.JButton cerrarBtn;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton verVueloBtn;
    // End of variables declaration//GEN-END:variables
}
